[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
definitions = { workspace = true }

clap = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
openssl = { workspace = true }
