name: Call a reusable workflow
on:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: sbailleul/chara_public/.github/workflows/build-workflow.yaml@main
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
