[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
definitions = { workspace = true }
engine = { workspace = true }
graph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
colog = { workspace = true }
