/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const GraphIndexLazyImport = createFileRoute('/graph/')()
const DefinitionIndexLazyImport = createFileRoute('/definition/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GraphIndexLazyRoute = GraphIndexLazyImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/graph/index.lazy').then((d) => d.Route))

const DefinitionIndexLazyRoute = DefinitionIndexLazyImport.update({
  id: '/definition/',
  path: '/definition/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/definition/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/definition/': {
      id: '/definition/'
      path: '/definition'
      fullPath: '/definition'
      preLoaderRoute: typeof DefinitionIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/definition': typeof DefinitionIndexLazyRoute
  '/graph': typeof GraphIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/definition': typeof DefinitionIndexLazyRoute
  '/graph': typeof GraphIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/definition/': typeof DefinitionIndexLazyRoute
  '/graph/': typeof GraphIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/definition' | '/graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/definition' | '/graph'
  id: '__root__' | '/' | '/definition/' | '/graph/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DefinitionIndexLazyRoute: typeof DefinitionIndexLazyRoute
  GraphIndexLazyRoute: typeof GraphIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DefinitionIndexLazyRoute: DefinitionIndexLazyRoute,
  GraphIndexLazyRoute: GraphIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/definition/",
        "/graph/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/definition/": {
      "filePath": "definition/index.lazy.tsx"
    },
    "/graph/": {
      "filePath": "graph/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
