[workspace]
members = ["app", "libs/engine", "libs/definitions", "libs/types"]

[workspace.dependencies]
definitions = { path = "libs/definitions" }
engine = { path = "libs/engine" }
types = { path = "libs/types" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
map-macro = "0.3.0"
